AddLogEntry Overloads
SubnauticaModding/Nautilus pull request #15
Opened 2023-04-29 22:18 UTC by LeeTwentyThree

### Changes made in this pull request

  - Added `public static void AddLogEntry(string key, string languageKey, Sound sound, Sprite icon = null)`
  - Added `public static void AddLogEntry(string key, string languageKey, AudioClip audioClip, Sprite icon = null)`
  - Added `public static void AddLogEntry(string key, string languageKey, string soundFilePath, Sprite icon = null)`
  - Added `public static void AddLogEntry(string key, string languageKey, IFModSound fmodSoundInterface, Sprite icon = null)`

Can someone with more knowledge on FMOD please review the logic of the added methods?

2023-04-30 09:19 UTC, Metious requested changes
Added some comments. The rest looks good to me.

2023-04-30 09:19 UTC, Metious commented on Nautilus/Handlers/PDAHandler.cs
> +    }
There are two problems with this code. 

Firstly, if there's already an existing custom sound registered with the same key, this method replaces it, but the previous sound will stay in memory causing a memory leak.

Secondly, the SoundQueue system (the one that's responsible for playing PDA sounds) uses the `id` part of the FMODAsset. Meaning in this case specifically, we have to pass an FMODAsset instance that sets the `id` field, not the `path`.

I suggest we change the logic so it only overrides the previous sound if they're not the same as the new one, if they aren't the same, we release the handle of the previous sound.
```suggestion
    public static void AddLogEntry(string key, string languageKey, Sound sound, Sprite icon = null)
    {
        /*
         * If there's an existing custom sound with the same key, we release the previous sound's handle.
         * This is so we do not leave any unused objects in memory.
         */
        if (CustomSoundHandler.TryGetCustomSound(key, out var prevSound))
        {
            if (prevSound.hasHandle() && prevSound.handle != sound.handle)
            {
                prevSound.release();
            }
        }
        
        CustomSoundHandler.RegisterCustomSound(key, sound, AudioUtils.BusPaths.PDAVoice);
        
        AddLogEntry(key, languageKey, AudioUtils.GetFmodAsset(key, key), icon);
    }
```

2023-04-30 09:19 UTC, Metious commented on Nautilus/Handlers/PDAHandler.cs
> +    /// <param name="fmodSoundInterface">The IFModSound interface that accessed when this log entry is played.</param>
You do not pass interfaces on the overload, you pass an object that _implements_ the `IFModSound` interface.

I think it's more fitting if the argument was named `fmodSound` and the docs description was the same as the [RegisterCustomSound(string, IFModSound)](https://github.com/SubnauticaModding/Nautilus/blob/master/Nautilus/Handlers/CustomSoundHandler.cs#L76) overload.

2023-05-01 02:01 UTC, LeeTwentyThree commented on Nautilus/Handlers/PDAHandler.cs
> +    }
`AudioUtils.GetFmodAsset(...)` already sets the ID and Path if the former is unassigned.

2023-05-01 02:21 UTC, LeeTwentyThree commented
I left commits addressing everything you mentioned. However I was a bit unsure on one of them so I left an [experimental commit](https://github.com/SubnauticaModding/Nautilus/pull/15/commits/16df22030971009aa2b12afb1f4844fd7bb5ecbd) with quite a lengthy description.

2023-05-02 02:12 UTC, LeeTwentyThree commented
Using your solution (reverted latest commit), but still not seeing the benefits of the Sound overload.

2023-05-03 20:39 UTC, Metious approved these changes

2023-05-03 20:40 UTC, merged