StoryGoal actions receive the name of the unlocked goal
SubnauticaModding/Nautilus pull request #476
Opened 2023-09-27 19:10 UTC by tinyhoot

### Changes made in this pull request

  - Custom events for StoryGoals behave as the documentation claims and now receive the name of the calling goal as an argument.

### Breaking changes

  - Method signature changes for both `RegisterCustomEvent()` and `UnregisterCustomEvent()`.

2023-09-27 20:36 UTC, Metious requested changes
As discussed [in the issue](https://github.com/SubnauticaModding/Nautilus/issues/475#issuecomment-1738040840), revert the breaking changes to the current methods, and just add two other overloads that only takes an `Action<string>`.

2023-09-28 00:06 UTC, tinyhoot commented
_Only_ an `Action<string>`? Without a key, any such method would receive the custom events of all other mods too.

2023-09-28 01:50 UTC, MrPurple6411 requested changes
Think these are the changes @Metious is meaning. 

Hopefully he will clarify if I am off base.

2023-09-28 01:50 UTC, MrPurple6411 commented on Nautilus/MonoBehaviours/CustomStoryGoalManager.cs
> +    internal static readonly Dictionary<string, List<Action<string>>> StoryGoalCustomEvents = new();
```suggestion
    internal static readonly Dictionary<string, List<Action>> StoryGoalCustomEvents = new();
    internal static readonly List<Action<string>> StoryGoalCustomKeyHandlerEvents = new();
```

2023-09-28 01:50 UTC, MrPurple6411 commented on Nautilus/MonoBehaviours/CustomStoryGoalManager.cs
>          foreach (var customEvent in StoryGoalCustomEvents)
```suggestion
        StoryGoalCustomKeyHandlerEvents.ForEach(x => x?.Invoke(key));

        foreach (var customEvent in StoryGoalCustomEvents)
```

2023-09-28 01:50 UTC, MrPurple6411 commented on Nautilus/MonoBehaviours/CustomStoryGoalManager.cs
> +                customEvent.Value.ForEach(x => x?.Invoke(key));
```suggestion
                customEvent.Value.ForEach(x => x?.Invoke());
```

2023-09-28 01:50 UTC, MrPurple6411 commented on Nautilus/Handlers/StoryGoalHandler.cs
Revert these changes and add 2 more instead that add/remove to/from the new List suggested in the other file.

2023-09-28 04:37 UTC, Metious commented
> _Only_ an `Action<string>`? Without a key, any such method would receive the custom events of all other mods too.

Isn't that the point? Perhaps I'm simply not familiar with your use-case, but I think it's useless to assign a key while also taking the key as a parameter in the delegate.

If the method only takes an `Action<string>`, you should be able to handle multiple goals in the same method. This is also the closest implementation to the vanilla custom goals implementation, so it's fine for those delegates to be callbacked on every goal.

It's a feature, not a bug :)

2023-09-28 18:24 UTC, tinyhoot commented
> It's a feature, not a bug :)

That's a good point! I've incorporated both of your suggested changes into this. The documentation for the method which only takes an `Action` also no longer claims that a parameter will be passed.

Please let me know if there's anything else I can adjust.

2023-09-28 18:28 UTC, MrPurple6411 commented
hrmmm @Metious Do we want the keyhandlers to run before or after the regular ones.

2023-09-28 18:54 UTC, Metious approved these changes
Lgtm.

2023-09-28 21:37 UTC, MrPurple6411 approved these changes

2023-09-28 21:39 UTC, merged