FMOD fade-outs
SubnauticaModding/Nautilus pull request #564
Opened 2024-11-10 07:02 UTC by Metious

### Changes made in this pull request

  - The game now respects fade-out points for custom sounds.

You can add a fade-out point using one of the two methods:
1. Directly on the `Sound` object when you're creating one. This makes the Sound always fade-out when fading is allowed
2. On the Channel object after the sound is played. This approach is manual and only applies the fade-out once.

### **REQUIRES THOROUGH TESTING**

2024-11-12 06:04 UTC, LeeTwentyThree requested changes
Needs a fix.

2024-11-12 06:04 UTC, LeeTwentyThree commented on Nautilus/Patchers/CustomSoundPatcher.cs
> +
```suggestion

channel.getDelay(out ulong _, out ulong _, out bool stopChannels);
        
if (stopChannels)
    return false;
    
```

This prevents unnecessary and conflicting fade points from cluttering the sound channel.

2024-11-13 03:08 UTC, LeeTwentyThree approved these changes

2024-11-13 03:08 UTC, merged

2024-12-23 07:13 UTC, JKohlman commented on Nautilus/Patchers/CustomSoundPatcher.cs
> +        public static bool FMOD_CustomEmitter_Stop_Prefix(FMOD_CustomEmitter __instance, STOP_MODE stopMode)
Causes #573. This method in BZ doesn't take a STOP_MODE parameter.